### ISSUE TITLE
Make it available through FDroid

### ISSUE THREAD

**Issue by robertgzr** [youkai-app/Youkai#36]
Since Youkai is open-source and all it would be nice to have it on there...

https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included

**Comment by xiprox** [comment]
Hello. 

Unfortunately, we aren't interested in putting the app up on F-Droid any time in the future. It's of no real benefit to us and is only extra pain.

That said, Youkai isn't anywhere near done or usable to begin with. We are using the Play Store for easy testing of the latest state of the code. It's not a _release_.
